# Generated by Django 5.0.2 on 2025-04-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('MO', 'Medical Officer'), ('C', 'Consultant'), ('SC', 'Sr. Consultant')], max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('visit_amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
